### ISSUE TITLE
Permanent QuickCursor concept / suggestion

### ISSUE THREAD

**Issue by ghost573** [micku7zu/QuickCursor#11]
Found your app, bought the pro license and it somewhat fulfills my needs but I was actually looking for something that Quick Cursor partially does and would like to make a suggestion for a mode that fits my niche use case.

![concept](https://user-images.githubusercontent.com/108908286/218221053-4f2675d1-21b0-48d4-bb43-628ef3a87fa0.png)

Size for everything is adjustable but the generally idea is for Quick Cursor to be permanently "mounted" to the bottom of the phone where your thumb can easily manage to move around and instead of mapping movements 1:1, it becomes basically a mouse cursor with the space QC takes acting as a trackpad on a laptop, so for example if you need to reach near the bottom you can just "scroll" the mouse to it and use the available functions of tap, swipe to navigate.

My idea comes from [The Big Phone Problem](https://www.youtube.com/watch?v=xgCo4ITSDVQ) where the concept is to remove all direct interactions with the device so it can be fully navigated one handed, this takes away majority of issues with one handed use on modern phones, QC currently partially fulfills this but for example if I have to tap something to either the far left / right, QC kind of gives up since you're not really moving a "mouse" but just extending your normal movements X amount of pixels.

Tracker Actions can be mapped to open if you long press in the "trackpad" area, maybe you can have an option to disable the navbar completely and have all functions mapped in Tracker Actions for a more seamless experience.

I don't know much of how Android dev works so many there are no APIs that support what I'm asking for but another example that somewhat showcases what I'm asking for is the [Samsung Z Flip 4 touchpad](https://www.youtube.com/watch?v=8jb86uwSks8) please mute the audio, it's terrible.

Sorry for the wall of text, looking forward to hearing how feasible this is.

**Comment by micku7zu** [comment]
Thanks for buying the pro and for support!

I must admit this is an interesting concept, but as you guessed, there are things that third party apps can't implement. If you check some of the open issues in Quick Cursor, a lot of them are Android limitations or bugs in different manufacturers Android implementation. Many great ideas were abandoned or not implemented because of limitations of a third party app. Also, some ideas were still implemented but with a lot of hacks/workarounds.

If Quick Cursor would have been integrated/developed inside the OS itself, it would have been much better.

About your concept, I think it is really good, even if I still prefer QC concept, I understand the need and how people would prefer it that way. 

An always visible trackpad overlapping stuff on the screen it is possible, and there are already apps on the Play Store offering this, but adding the trackpad on the bottom and moving the other parts of the screen (app content or navbar) I don't think it is possible. Maybe there are some weird hacks to do this with or without root, but I don't think they are good enough to start an app on them. 

Quick Cursor is conceptual a pretty simple app, and should be really easy to develop, but the reality is that all the hacks needed on all the different Android versions and manufacturers difference it is a nightmare to support. Even a simple "keyboard open/close detection" mechanism had to be rewritten 3 or 4 times during the QC life time, because of changes in Android and Android not offering this as an API for apps that don't run in the foreground. The current keyboard detection mechanism is still a hack that I hope will work properly on the next Android versions. 

I started QC app as a hobby project to replace Reachability Cursor for myself, because I used Reachability Cursor and it was not working anymore on newer Android versions and I needed a replacement. After I had a working version I saw that there are other users like me that needed a replacement and I decided to make it public + pro version for some monetizing to make me ambitious to develop it more, but I never expected all the work needed to support an app like this (background accessibility app with all the hacks). 

> Sorry for the wall of text, looking forward to hearing how feasible this is.
- I don't think it is feasible to add a trackpad under navbar/app content and move everything up because of Android limitations for third party apps. For manufacturers/custom rom to implement this in their versions would be a good choice.  
- I think everything else it is feasible, an always visible trackpad overlapping the screen content. This is already offered by some Play Store apps.
- Quick Cursor to support trackpad option in the future? I'm not sure yet. The app can be adapted to work with this of course, but it will complicate everything too much based on how much free time I have to support this app, being an hobby project and the revenue clearly don't support me enough to transform it in a half/full time job. 
- Another separate app like Quick Cursor but with trackpad support? No, I don't have enough time to support two apps like this. 

Every time I have to add a new feature in Quick Cursor I have to double check how much support that feature will need or how much will complicate everything inside the app. Implementing the feature is the smallest part of it, supporting it in the future is the most time consuming part. 

I never know how things will change in the future, if the app will become a huge success and it will be profitable enough (it still has a lot of potential to grow), I will have more time to invest in development and support. 

The majority of the work in this app was driven by passion/hobby/personal need and not by revenue. [Here are some info about the revenue of the app](https://www.reddit.com/r/androiddev/comments/zhkgww/how_much_have_you_made_from_your_apps/izn4qar/) for anyone interested.

I hope I'm not misunderstood, I don't want to influence anyone who wants to start to develop an app like this, I just present my own data openly for anyone to analyze and take their own decission. For me, this was overall the most successfull project. It gave me a lot of satisfaction because I made an application for my own needs, a lot of users appreciated it and I also got some extra money from it.

**Comment by micku7zu** [comment]
I deviated a bit at the end, what I wanted to say is that adding a feature in Quick Cursor or to create a separate app it has to check one of this conditions:

- [ ] 1. a feature that I personally need in the app
- [ ] 2. a feature that even if I will not use or need, I understand its usefulness and it is easy to develop and support in the future
- [ ] 3. a feature that it is worth based on time invested/revenue outcome

All the Quick Cursor app features were 1. or 2. so far, because the revenue raport is not yet worth. So, at the moment this is not doable for me, because it is not a feature easy to support in the future, it changes a lot of internal things of Quick Cursor.

But this can be a good idea for someone who wants to start a new app like this, because the concept is good and it may be preferred over QC ways of working based on user preferences. 

Thanks for feedback! I appreciate it!

**Comment by micku7zu** [comment]
**Also disclaimer: I'm not a full time Android developer**, it is just a hobby or side project. My full time job and most experience is in web development. 

Opinions above on what can be achieved and not in Android are based on my past 3 years of Quick Cursor development and investigations, so they might be wrong.

**Comment by ghost573** [comment]
Thanks for the reply.

I don't know how limited Android as an OS is so my idea is from a user standpoint and I didn't want to try and suggest this idea to community projects like LineageOS since they're all quite strict in what new features they add or even carry over from previous versions, less and less features are carried over as time goes on.

Might be a long shot but since you developed it, you might have a better shot at suggesting it to teams like LineageOS to have it directly implemented as a feature instead of a user but then again the idea of one-handed use seems to be niche nowadays as per the video I linked.

Otherwise it looks like my idea to have a method to fully eliminate direct interaction is somewhat not feasible or feasible but with lots of hacks and workarounds that can potentially be patched out by Google at the AOSP base at any time.

Even if you can't personally work on it, I'm happy you took the time to respond and hear my idea out.
